### ISSUE TITLE
River UI container - how to disable a startup log

### ISSUE THREAD

**Issue by rtrzebinski-usc** [riverqueue/riverui#267]
Hi, I run riverui as a side container of a pod deployed to a k8s cluster.

Every time this container starts it writes this to the output:

```
river-ui 2025/01/08 12:48:39 starting server on :8080
```

The problem is that this is considered an error by Data Dog and is triggering an alert every time the pod is created.

I tried to use new `RIVER_LOG_LEVEL` setting to suppress it, but it does not seem to do anything.

This is my configuration:

```
  river-ui:
    name: river-ui
    image:
      repository: ghcr.io/riverqueue/riverui
      tag: 0.7.0
    env:
      - name: RIVER_LOG_LEVEL
        value: "error"
```

Would you please advise how to remove this problematic output, thank you.
